# Path to your oh-my-zsh installation.
export TERM="xterm-256color"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  bundler
  dotenv
  osx
  rake
  rbenv
  ruby
#  zsh-autosuggestions
#  zsh-syntax-highlighting
  colored-man-pages
)

# User configuration
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

# theme
ZSH_THEME="powerlevel9k/powerlevel9k"
export ZSH=~/.config/zsh/oh-my-zsh
source ~/.config/zsh/powerlevel9k
source $ZSH/oh-my-zsh.sh

# kubernetes config
source ~/.config/scripts/kube_config.sh

# alias
alias vi="nvim"
alias vim="nvim"
alias ls="exa"
alias cat="bat -p"
alias du="ncdu -q"

# ssh
function ssh () {/usr/bin/ssh -t $@ "tmux attach || tmux new || zsh || bash";}
function key () {cat ~/.ssh/id_rsa.pub|pbcopy}

# fzf
[ -f ~/.config/fzf/fzf.zsh ] && source ~/.config/fzf/fzf.zsh

# tmux
[ -z "$TMUX" ] && ( tmux -f ~/.config/tmux/tmux.conf attach -t TMUX || tmux -f ~/.config/tmux/tmux.conf new -s TMUX )
